./createMoodle.sh -t CEIP -u https://cracunajiloca.aeducar.es/ "CUNA JILOCA"
./createMoodle.sh -t CPI -u https://cpiparquevenecia.aeducar.es "PARQUE VENECIA"  
./createMoodle.sh -t CEIP -u https://ceipfcogoya.aeducar.es/ "FRANCISCO GOYA"
./createMoodle.sh -t CEIP -u http://ceipemil  iomorenocalvete.aeducar.es "EMILIO MORENO CALVETE"
./createMoodle.sh -t CEIP -u https://ceipzurita.aeducar.es/ "ZURITA"
./createMoodle.sh -t CEIP -u https://crarioribota.aeducar.es/ "RIO RIBOTA"
./createMoodle.sh -t CPI -u https://ceesegeda.aeducar.es/ "SEGEDA"
./createMoodle.sh -t CEIP -u https://ceipgasconymarin.aeducar.es/ "GASCÓN Y MARÍN"
./createMoodle.sh -t CEIP -u https://ceipmiguelartazos.aeducar.es/ "MIGUEL ARTAZOS"
./createMoodle.sh -t CEIP -u https://crapuertadearagon.aeducar.es/ "PUERTA DE ARAGÓN"
./createMoodle.sh -t CEIP -u https://ceipsobradiel.aeducar.es/ "SUBPRADEL"
./createMoodle.sh -t CEIP -u https://ceipramirosolans.aeducar.es/ "RAMIRO SOLANS"
./createMoodle.sh -t CPI -u https://craaltomaestrazgo.aeducar.es/ "ALTO MAESTRAZGO"
./createMoodle.sh -t CEIP -u https://ceippabloluna.aeducar.es/ "PABLO LUNA"
./createMoodle.sh -t CEIP -u https://ceipinfantaelena.aeducar.es/ "INFANTA ELENA"
./createMoodle.sh -t CEIP -u https://ceippedrojrubio.aeducar.es "PEDRO J.RUBIO"
./createMoodle.sh -t CEIP -u https://ceipelparque.aeducar.es/ "EL PARQUE"
./createMoodle.sh -t CEIP -u https://www.colegranen.aeducar.es "SANTIAGO APOSTOL"
./createMoodle.sh -t CEIP -u https://escueladeartehuesca.aeducar.es "ESCUELA DE ARTE"
./createMoodle.sh -t CEIP -u https://cpzaidin.aeducar.es "SAN JUAN BAUTISTA"
./createMoodle.sh -t CEIP -u https://ceipdiegoescolano.aeducar.es/ "DIEGO ESCOLANO"
